### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ubnt-michals** [vitaly-t/pg-promise#618] opened 2019-06-06 07:04 UTC
### Actual behavior
```
RangeError: Maximum call stack size exceeded
  File "/home/app/unms/node_modules/pg-promise/lib/events.js", line 361, col 25, in Object.error
    $events.unexpected('error', e);
  File "events.js", line 194, col 15, in Client.emit
  File "domain.js", line 441, col 20, in Client.EventEmitter.emit
  File "/home/app/unms/node_modules/pg/lib/client.js", line 148, col 10, in Connection.connectedErrorHandler
    this.emit('error', err)
  File "events.js", line 189, col 13, in Connection.emit
  File "domain.js", line 441, col 20, in Connection.EventEmitter.emit
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 71, col 10, in Socket.reportStreamError
    self.emit('error', error)
  File "events.js", line 189, col 13, in Socket.emit
  File "domain.js", line 441, col 20, in Socket.EventEmitter.emit
  File "_stream_writable.js", line 425, col 12, in onwriteError
  File "_stream_writable.js", line 456, col 5, in onwrite
  File "_stream_writable.js", line 406, col 11, in doWrite
  File "_stream_writable.js", line 394, col 5, in writeOrBuffer
  File "_stream_writable.js", line 294, col 11, in Socket.Writable.write
  File "/home/app/unms/node_modules/pg/lib/connection.js", line 320, col 22, in Connection.end
    return this.stream.write(END_BUFFER, () => {
  File "/home/app/unms/node_modules/pg/lib/client.js", line 489, col 21, in Client.end
    this.connection.end()
```

### Steps to reproduce
Unfortunately don't know.

It's hard to tell if the culprit is in `pg-promise` or `pg`/`pg-pool`. My guess is it's somehow related to reconnect - because of connect + connection.end()

### Environment
Full stack trace: https://sentry.io/share/issue/e6c43091e0b645549d03037bd9eef20b/

* Version of pg-promise: 8.5.5
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: v10.15.3

**Comment by vitaly-t** [comment] 2019-06-06 10:50
Possibly, because you are throwing an error while handling an error. Anyway, without steps to reproduce, it is not very useful.

**Comment by vitaly-t** [comment] 2019-07-05 13:01
Try to upgrade to the latest version, as there were some relevant changes. If you still can see the issue, then please provide steps to reproduce. Otherwise, there is nothing we can do about it. In the meantime, I am closing this issue.

**Closed by vitaly-t** 2019-07-05 13:01 UTC
