### ISSUE TITLE
Intermittent error from pg-promise

### ISSUE THREAD

**Issue by ubreddy** [vitaly-t/pg-promise#433] opened 2017-11-29 11:57 UTC
I use the following to connect to the azure postgres service.

bluebird:3.5.1
pg-promise : 5.9.7

The following error occurs intermittently..  after a while .. connection is established db is updated etc in the meanwhile. At regular times this error shows up.

How the db is connected?

```
var promise = require('bluebird');

var options = {
  // Initialization Options
  promiseLib: promise
};
var cn = {
  host: config.POSTGRES_DB_HOST, 
  port: config.POSTGRES_PORT,
  database: config.POSTGRES_DB_NAME,
  user: config.POSTGRES_DB_USERNAME,
  password: config.POSTGRES_DB_PASSWORD,
  ssl:true
};
var pgp = require('pg-promise')(options);
var pgdb = pgp(cn);

```

TypeError: Cannot read property 'options' of undefined
    at PG.onError (D:\home\site\wwwroot\node_modules\pg-promise\lib\database.js:1299:26)
    at emitTwo (events.js:106:13)
    at PG.emit (events.js:191:7)
    at PG.<anonymous> (D:\home\site\wwwroot\node_modules\pg\lib\index.js:67:12)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at .<anonymous> (D:\home\site\wwwroot\node_modules\pg-pool\index.js:93:10)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Connection.<anonymous> (D:\home\site\wwwroot\node_modules\pg\lib\client.js:174:19)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\pg\lib\connection.js:94:12)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)

What could be wrong ?

**Comment by vitaly-t** [comment] 2017-11-29 23:39
Duplicate of #396

**Closed by vitaly-t** 2017-11-29 23:39 UTC
