### ISSUE TITLE
Export query results to CSV file (using stream)

### ISSUE THREAD

**Issue by Juliocbr** [vitaly-t/pg-promise#664] opened 2019-10-26 10:42 UTC
Hi, 

I am new to the development of node and postgresql, my doubt is that I want to export the results of my query to a csv file, I have found that it is possible to do it efficiently using pg-copy-streams but I do not know if with the documentation provided by this library to use streams it is not necessary to use that library and it is only enough to do something similar to this:

```
const pgp = require('pg-promise')({
  // number idleTimeoutMillis - lifespan for unused connection
  //keepAlive - keep TCP alive
})
const QueryStream = require('pg-query-stream')
const JSONStream = require('JSONStream')

async function synchronizeData() {
const db = pgp(DATABASE_URL)

  const qs = new QueryStream(
    `
    COPY (
      select distinct p.id, u.created_at, a.share, a.created_on as share_on, p.username, up.email, up.name, up.surname, up.second_surname, up.birthday, up.gender, up.country_code
      from profile_share_personal_info_history a, profile p, users u, user_profiles up, synchronized_tables st
      where a.created_on =
      (
        select max(b.created_on)
        from profile_share_personal_info_history b
        where a.profile_id = b.profile_id
      )
      and a.profile_id = p.id and u.username = p.username and u.id = up.user_id
      and (u.created_at >= st.synchronized_at or st.synchronized_at is null) and st.table_name='Profile'
    )
    TO '${pathProfileCSV}'
    WITH (FORMAT csv, DELIMITER ',', HEADER true, ENCODING 'UTF-8')
  `
  )

  db.stream(qs, s => {
    // initiate streaming into the console:
    s.pipe(JSONStream.stringify()).pipe(process.stdout)
  })
    .then(data => {
      console.log('Total rows processed:', data.processed, 'Duration in milliseconds:', data.duration)
    })
    .catch(error => {
      console.log('ERROR:', error)
    })
}

synchronizeData()
```

### Environment

* Version of pg-promise: 8.6.4
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.15.0

Thanks.

**Comment by vitaly-t** [comment] 2019-10-26 20:07
Duplicate of #527, #122

**Closed by vitaly-t** 2019-10-26 20:07 UTC
Labels: duplicate
