### ISSUE TITLE
Nested transaction behavior - maybe incorrect?

### ISSUE THREAD

**Issue by vertiman** [vitaly-t/pg-promise#57] opened 2015-10-22 16:28 UTC
I have a situation that kind of looks like this...  (stole this from the pg-promise tests)

```
db.tx(function (t1) {
    context1 = this;
    return this.none('update users set login=$1', ['External']).then(function () {
        return context1.tx(function (t2) {
            return t2.none('update users set login=$1', ['External']) 
        });
    }).then(function () {
        return context1.one('select * from unknowntable') // emulating a bad query;
    })
})
```

The premise - it creates a transaction, then does something, then creates an inner transaction that does something else, then finishes the inner transaction, then does something else which causes the outer transaction to rollback.  I know it's a contrived situation, but when you have situations involving other dependant methods the composition does make sense.  This is just a simplified form.

The pg-monitor outlook looks like this...

12:21:30 tx/start
12:21:30 tx: begin
12:21:30 tx: update users set login='External'
12:21:30 tx/start
12:21:30 tx: begin
12:21:30 tx: select * from users
**12:21:30 tx: commit**
12:21:30 tx/end; duration: .004, success: true
12:21:30 tx: select * from unknowntable
12:21:30 error: relation "unknowntable" does not exist
         tx: select * from unknowntable
12:21:30 tx: rollback
12:21:30 tx/end; duration: .013, success: false

You can see in the bolded line that pg-promise finishes the inner transaction and issues a commit.  This is incorrect behaviour as there is an outer scope in play, and PG does not support nested transactions.  This commit actually commits the initial outer scope update, as well as commiting the inner scope.  Shouldn't it hold the commit until the outer transaction completes?

Any advice on this situation?  Thanks!

**Comment by vitaly-t** [comment] 2015-10-22 19:28
I don't think the inner transaction works the way you think it does.

This situation has been covered by [this test](https://github.com/vitaly-t/pg-promise/blob/master/test/dbSpec.js#L721)

`COMMIT` of the inner transaction is ignored when the parent transaction does `ROLLBACK`.

**Comment by vertiman** [comment] 2015-10-22 19:31
I don't think that is true, commit of the inner transaction is not ignored when the parent does a rollback.  There is no such thing as an inner transaction in PG.  That test you referred to passes because the inner transaction fails, not the outer transaction.

Here's a full test showing what I mean.  I'm working on a strategy to patch this now... we'll see if you like it.  This test fails right now, with all the db entries being set to "Internal" even though they should remain as "Before" since the outer tx rolls back.

```
describe("When an outer transaction fails that has a nested transaction", function () {
    it("both transactions must rollback", function () {
        var result, context1;

        db.none('update users set login = $1', 'Before').then(function () {
            return db.tx(function (t1) {
                context1 = this;
                return this.none('update users set login=$1', 'External').then(function () {
                    return context1.tx(function (t2) {
                        return t2.none('update users set login=$1', 'Internal')
                    });
                }).then(function () {
                    return context1.one('select * from unknowntable') // emulating a bad query;
                })
            })
                .then(function () {
                    result = null; // must not get here;
                }, function () {
                    return promise.all([
                        db.one('select count(*) from users where login=$1', 'External'), // 0 is expected;
                        db.one('select count(*) from users where login=$1', 'Internal'), // 0 is expected;
                        db.one('select count(*) from users where login=$1', 'Before') // > 0 is expected;
                    ]);
                })
                .then(function (data) {
                    result = data;
                });
        });


        waitsFor(function () {
            return result !== undefined;
        }, "Query timed out", 5000);

        runs(function () {
            expect(result).toBeTruthy();
            console.log(result[0], result[1], result[2]);
            expect(result[0].count == 0).toBe(true);
            expect(result[1].count == 0).toBe(true);
            expect(result[2].count > 0).toBe(true);
        });
    });
});
```

**Comment by vertiman** [comment] 2015-10-22 19:34
Even more importantly, that test could be structured to show that if the statement that updated values to External wasn't completely overwritten by the statement that sets values to internal (if they used different data), both of those statements would be committed, even though the outer TX rolls back.

**Comment by vitaly-t** [comment] 2015-10-22 19:39
Just on my previous response, please post an updated log, using tagged transactions, so we can see more clearly the execution chain, without making assumptions.

**Comment by vertiman** [comment] 2015-10-22 19:41
Sorry, I'm not sure what you're asking me to do?  Happy to help, just unsure.
How do I use tagged transactions?

**Comment by vitaly-t** [comment] 2015-10-22 19:42
I have provided the code example for you above, already updated. You can see `"first"` and `"second"` injected tags before each transaction. This will change the log accordingly.

**Comment by vertiman** [comment] 2015-10-22 19:49
---------------------------15:47:03 connect(mwertman@pg_promise_test)
15:47:03 update users set login = 'Before'
15:47:03 disconnect(xxx@pg_promise_test)
15:47:03 connect(xxx@pg_promise_test)
15:47:03 tx(outer)/start
***15:47:03 tx(outer): begin***
15:47:03 tx(outer): update users set login='External'
15:47:03 tx(inner)/start
***15:47:03 tx(inner): begin***
15:47:03 tx(inner): update users set login='Internal'
***15:47:03 tx(inner): commit***
15:47:03 tx(inner)/end; duration: .002, success: true
15:47:03 tx(outer): select * from unknowntable
15:47:03 error: relation "unknowntable" does not exist
         tx(outer): select * from unknowntable
***15:47:03 tx(outer): rollback***
15:47:03 tx(outer)/end; duration: .007, success: false

Here you go.  Per PG spec, when the second BEGIN is issued it will issue a warning, and notify that no new txn is created, then when the first COMMIT issued, it commits the entire transaction, before it then fails and issues a ROLLBACK with no active transaction.

**Comment by vertiman** [comment] 2015-10-22 19:50
I actually have a fix for this behavior, I just tested it.  Let me make a PR and let me know if you think it's in the right spot, or if there is a better spot for it.

**Comment by vitaly-t** [comment] 2015-10-22 19:51
@vertiman I'm gonna look at it closely when I'm back in about 4 hours. Post any details in the meantime that you think are relevant ;)

**Comment by vertiman** [comment] 2015-10-22 19:53
@vitaly-t Thanks for being so responsive.  PR will be up in a few minutes.  Your library rocks, I'm happy I can contribute!

**Comment by vitaly-t** [comment] 2015-10-22 23:45
@vertiman Thank you for pointing at this issue. As I had a chance to look at it in detail, I can see now that the problem is more serious than I thought, and your PR won't fix it.

According to the official documentation about nested transactions, `SAVEPOINT` commands must be used, and not another `BEGIN`/`COMMIT`/`ROLLBACK`.

I don't know how I've missed it, and what's worse, the tests didn't bring this up either.

I have started working on making the necessary changes to address the issue, and will let you know when it is ready. But it looks like a major change/fix.

**Comment by vertiman** [comment] 2015-10-23 00:07
What is your intended behaviour though?  Given the nature of promises and rejection, I don't know if SAVEPOINTS is the right approach.  The PR essentially limited any db connection to a single nesting of transaction (only 1 BEGIN/ COMMIT / ROLLBACK would occur per nested set), and if an error bubbled up to the outer transaction it rolled back the whole thing.  I figured that would be the desired behaviour.

The only situation you'd want to use SAVEPOINT for would be continuing the outer txn in the event an inner TXN failed.  It seems like potentially a valid case, but would be quite complex to model effectively.

**Comment by vertiman** [comment] 2015-10-23 00:08
PS - at a minimum cherry pick in the unit test I added in the PR.  It will fail for improperly behaving nested transactions.

**Comment by vitaly-t** [comment] 2015-10-23 00:20
The official documentation says - you have got to use `SAVEPOINT` for inner transactions. I don't think there any work-around it. This is the only right way to do it, it seems, and I'm looking at implementing it.

**Comment by vertiman** [comment] 2015-10-23 01:58
What about this - https://github.com/vertiman/pg-promise/commit/ca40929e2ea84cdc9ccf0e1ae95d59ce3d59b617

The design makes it so if you catch the error off the inner .tx() it will allow the outer to commit, even though it did the savepoint rollback, but if you don't catch it it will throw the rejection all the way up and roll back the whole transaction.  I think it covers all the cases now?

Let me know and I can send a PR.

**Comment by vitaly-t** [comment] 2015-10-23 02:56
Something along those lines, but I have to see everything working together first. And that includes proper execution of `release savepoint` and `rollback to savepoint`, which you didn't even include.

Anyhow, i'm working on it, and I will need all the relevant tests in place before committing the changes.

**Comment by vitaly-t** [comment] 2015-10-23 03:44
@vertiman 

I have created a new branch [nested_tx](https://github.com/vitaly-t/pg-promise/tree/nested_tx), and committed all the changes needed to fix the issue.

I will do another review of it later and update all the tests, before merging it into the master branch.

So far it seems to be working in all the cases I tested it against. Since savepoints rely on the transaction level, I called all automatic labels `level_1`, `level_2`, etc, which corresponds to the transaction level.

**Comment by vitaly-t** [comment] 2015-10-23 05:24
@vertiman the issue has been fixed in [v.2.2.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.2.2.0).

**Closed by vitaly-t** 2015-10-23 05:24 UTC
Labels: bug, low frequency

**Comment by vitaly-t** [comment] 2015-10-23 16:29
@vertiman did you have a chance to test the new release on your side?

**Comment by vertiman** [comment] 2015-10-23 16:32
Just finalizing it all now.  There might be a minor issue with pg-monitor not showing rollback, but otherwise I think the behaviour is pretty clean.  Thanks for the quick turnaround.

Will update you on the pg-monitor thing in a few minutes.

**Comment by vertiman** [comment] 2015-10-23 16:36
Never mind - it's all good.  Thanks again!

**Comment by vitaly-t** [comment] 2015-10-24 01:12
Thanks for reporting back!

**Comment by vitaly-t** [comment] 2015-11-24 09:56
@vertiman Version 2.4.2 added an important note regarding the [limitation of nested transactions](https://github.com/vitaly-t/pg-promise#limitations).

**Comment by vertiman** [comment] 2015-11-24 14:27
@vitaly-t thanks for the update, looks good!

**Comment by vitaly-t** [comment] 2015-11-24 20:18
@vertiman You are welcome! I have re-written that chapter several times since then, because it makes a crucial point about nested transactions.

**Comment by vertiman** [comment] 2015-11-24 20:34
@vitaly-t you do a good job explaining it, but why not just defer to the postgres documents (or at least link to them?).  I think the most important part of your new chapter is the very last line, outlining how pg-promise behaves with regards to nested transaction blocks.

**Comment by vitaly-t** [comment] 2015-11-24 20:37
@vertiman PostgreSQL official documentation doesn't state it clearly that they do not have proper support for nested transactions, call it a marketing step, so I had to explain it myself :)

**Comment by vertiman** [comment] 2015-11-24 20:43
Wow, you're right.  It's pretty subtle... Issuing BEGIN when already inside a transaction block will provoke a warning message. The state of the transaction is not affected. To nest transactions within a transaction block, use savepoints (see SAVEPOINT).

**Comment by vitaly-t** [comment] 2015-11-24 20:44
@vertiman yep :)

**Comment by vitaly-t** [comment] 2021-02-28 00:53
#744 - some bearing on how savepoints are named.
