### ISSUE TITLE
Mixing Up Streaming example not working? Help with reading massive data 

### ISSUE THREAD

**Issue by shaunakv1** [vitaly-t/pg-promise#502] opened 2018-04-09 05:42 UTC
Hello @vitaly-t , 

Here's my use-case: 

1. I have a table of 2+ million rows 
2. I need to stream one row at a time, process it with some data form my redis instance
3. Insert the row back in a new table. 

I am stuck on the reading form source table part. I am trying to use this [example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#mixing-up)  form the documentation to achieve this, however the example doesn't seem to be working as expected. Please excuse my naivety , my experience with streams is very limited. 

I am referring to this [example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#mixing-up) in the documentation : 

Annotated code example from above linked documentation:

```js
const QueryStream = require('pg-query-stream');
const streamRead = pgp.spex.stream.read;
const qs = new QueryStream('SELECT * FROM users');

function receiver(_, data) {
    console.log('USER:', data[0]); //<--------- Doesn't print anything.
     
     /**
      * 1. I want to get each row here from table with 2+ million rows
      * 2. Massage the data (using data form my redis instance)
      * 3. Insert back into a new table 
      */
}

db.stream(qs, s => {
        return streamRead(s, receiver);
    })
    .then(data => {
        // success;
        console.log('Total rows processed:', data.processed, 'Duration in milliseconds:', data.duration);
    })
    .catch(function (error) {
        // error;
    });
```

### Expected behavior
  Hoping to see the console log with at-least first row in the `receiver` function. 

### Actual behavior
  Log doesn't actually print. The `receiver` function doesn't seem to be called either.  In both code example the stream processed callback does get called that prints "Total rows processed..."

### Alternate approach 

Here's another version of this function I tried based on your guidelines of how `getNextData` function should behave in [Data Import](https://github.com/vitaly-t/pg-promise/wiki/Data-Imports) page and 
[sequence](http://vitaly-t.github.io/spex/global.html#sequence) docs.

```js
const qs = new QueryStream("SELECT id, username, address FROM user;");
this.db.stream(qs, s => {
    //s.pipe(JSONStream.stringify()).pipe(process.stdout); //<---- this seems to work
    return this.streamRead(s, function(_, data) {
        //this callback never seems to get called
        function getNextData(index) {
            if (index < data.length) {
                console.log(data[index]);
                return Promise.resolve(data[index]);
            } else Promise.resolve(null);
        }

        function dest(index, data, delay) {
            console.log('LOG:', index, data, delay);
        }
        return this.sequence(getNextData, { //<<--------- Is calling sequence on this, correct? 
            dest: dest,
            track: true
        });
    });
}).then(data => {
    console.log('Total rows processed:', data.processed, 'Duration in milliseconds:', data.duration);
}).catch(this.errorHandler);
```

Can you please provide a more specific example that fully shows how to use sequence to read the stream, or help spot what am doing wrong? I did refer to couple of other tickets like https://github.com/vitaly-t/pg-promise/issues/434 and  https://github.com/vitaly-t/pg-promise/issues/493 but with no luck. In https://github.com/vitaly-t/pg-promise/issues/493 you do provide some explanation but I am unable to use it to fix this.  I tried passing `qs` straight to `pgp.spex.stream.read` but get exact same behaviour. 

### Environment

* Version of pg-promise:
pg-promise version "8.2.2"
  dependencies:
    manakin "0.5.1"
    pg "7.4.1"
    pg-minify "0.5.4"
    spex "2.0.2"

* OS type Mac

* Version of Node.js: v8.10.0

**Comment by vitaly-t** [comment] 2018-04-09 05:55
What is the version of `pg-query-stream` that you are using?

**Comment by shaunakv1** [comment] 2018-04-09 06:04
```
pg-query-stream@^1.1.1:
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/pg-query-stream/-/pg-query-stream-1.1.1.tgz#65e97436ef809d1e160eba84ebf11b9e4742eab4"
  dependencies:
    pg-cursor "1.3.0"
```

**Comment by vitaly-t** [comment] 2018-04-09 06:10
Cheers, that all seems fine, at first sight. I will only be able to run some tests on this about 10 hours from now. I will post results here, or maybe you will find something in the meantime :wink:

**Comment by shaunakv1** [comment] 2018-04-09 06:12
Awesome, I really appreciate your quick response and looking further into this. I will keep watching. Thanks much!

**Comment by vitaly-t** [comment] 2018-04-09 17:08
I was able to reproduce the issue. It seems that all the work-around I did following [this issue](https://github.com/brianc/node-pg-query-stream/issues/37) wasn't quite enough.

Unfortunately, that library's author is barely ever seen doing anything for his libraries, which is very frustrating. And unless that module is fixed to support readable streams, I cannot do anymore work-around on my end, because this time I'm not sure it is even possible.

**Comment by vitaly-t** [comment] 2018-04-09 17:29
@shaunakv1 I wouldn't be upset about this whole issue, because that stream library is crap anyway, because it soaks everything in before it starts streaming, so it is not a real streaming anyway.

If you've got too much data to get out of the database, you can always page your requests, using `OFFSET` + `LIMIT` :wink:

**Comment by shaunakv1** [comment] 2018-04-10 02:07
@vitaly-t wise words :) streaming probably was not what I needed but just wanted! Going old school like you suggested and paging the database with `OFFSET` + `LIMIT` worked beautifully.  Especially when using with [spex sequence](http://vitaly-t.github.io/spex/tutorial-throttling.html) it worked like a charm 👍 

I am going to post my solution here for anyone who needs a good example of massive data retrieval and batch processing. @vitaly-t please give this a look and suggest any improvements you can think of to make this more elegant. 

Solution: 

```sql
 -- userCount.sql
SELECT count(*) as count FROM user_dumps;
```

```sql
 -- usersPaged.sql
SELECT id, username, address
FROM users
LIMIT ${limit} OFFSET ${offset};
```

```js 
//db/repos/users.js

'use strict';
const sql = require('../sql').users;
class Users {
    constructor(db, pgp) {
        this.db = db;
        this.pgp = pgp;
    }
    getUserCount() {
        return this.db.one(sql.userCount).then(data => {
            return data
        }).catch(this.errorHandler);
    }
    getUserInBatch(onUsersAvailable) {
        return this.db.task(t => {
            return t.one(sql.userCount).then(userCount => {
                let pageSize = 10;
                let numOfPages = parseInt(userCount / pageSize);
                const source = (index) => {
                    return new Promise(function(resolve, reject) {
                        t.any(sql.usersPaged, {
                            limit: pageSize,
                            offset: index * pageSize
                        }).then(data => {
                            let res = {
                                users: data,
                                page: index
                            }
                            //send this batch of users back to client for processing
                            onUsersAvailable(res, function(someDataToInsertBackInDatabase) {
                                //client calls this callback to indicate
                                //that it has finished processing this batch
                                //and send data to insert back in new table as arguemnt
                                //and to send it next batch
                                resolve(someDataToInsertBackInDatabase);
                            });
                        });
                    });
                }
                const postProcess = (index, data, delay) => {
                    console.log(`Post Process batch: ${index} users:${data.count}`);
                }
                return t.sequence(source, {
                    dest: postProcess,
                    limit: numOfPages
                })
            })
        }).catch(this.errorHandler);
    }
    errorHandler(error) {
        console.error(error);
        return {
            error: error,
            message: error.message
        };
    }
}
module.exports = Users;
```

```js
//client.js

const db = require('../db');

db.users.getUserInBatch(function(data, getPostProcessAndGetNextBatch) {
    console.log(`Batch: ${data.page} : ${data.users.length} users`);
    getPostProcessAndGetNextBatch({
        count: data.users.length
    });
}).then(() => {
    console.log('All Done!');
    db.disconnect();
});


```

```bash

#Sweet output you want to see :)
➔ yarn run match

Users in Database: 2439991
Batch: 0 : 10 users
Post Process batch: 0 users:10
Batch: 1 : 10 users
Post Process batch: 1 users:10
Batch: 2 : 10 users
Post Process batch: 2 users:10
Batch: 3 : 10 users
Post Process batch: 3 users:10
Batch: 4 : 10 users
Post Process batch: 4 users:10
All Done!

✨  Done in 1.23s.

#this is run over just a subset of data for demo
```

For anyone wondering how these files work together check out [awesome demo](https://github.com/vitaly-t/pg-promise-demo/tree/master/JavaScript) by @vitaly-t 

Not sure if we still want to keep this open until the streaming issue is fixed, so people can refer to the solution or you would like to close this ticket. I am okay either way.  

Finally, thanks again @vitaly-t. Being a heavy user of OpenSource code, I have worked with quite a few popular libraries but I have never seen anyone as dedicated and prompt in providing support for their project as you! Cheers, and keep up the awesome work on pg-promise.

**Comment by vitaly-t** [comment] 2018-04-10 12:35
This is a nice attempt ;)

Of course there is always room for improvements. For example, if your `onUsersAvailable` returns a promise, then you can simplify the chain, and not create an extra promise inside `getUserInBatch`.

Also, method `sequence` as mainly valuable for unlimited/dynamic sequences. When you specify explicit `limit`, it means your sequence can be simplified to a regular while/loop.

---

I'm closing the issue in the meantime, because there not going to be any progress in a foreseeable future, until the day `pg-query-stream` is fixed, which I do not expect any time soon.

**Closed by vitaly-t** 2018-04-10 12:35 UTC
Labels: dependency issue
