### ISSUE TITLE
Using Buffer without `new` will soon stop working.

### ISSUE THREAD

**Issue by paleite** [vitaly-t/pg-promise#242] opened 2016-11-25 16:36 UTC
Hey, I'm getting a warning when using pg-promise.

I'm using `node@7.2.0` and `pg-promise@5.4.3`.

> var pgp = require('pg-promise')();

yields the following output:

> (node:60294) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by MitMaro** [comment] 2016-11-25 18:56
I believe this is a duplicate of #234

**Comment by vitaly-t** [comment] 2016-11-25 23:11
@MitMaro thnaks, it is a duplicate indeed.

@paleite it will get attention by the time Node.js 7.x becomes an LTS ;)

Granyed, the driver's support is less than good these days, so I'm looking at alternatives.

**Closed by vitaly-t** 2016-11-25 23:11 UTC

**Comment by vitaly-t** [comment] 2016-12-09 22:52
Version 7.2.1 of Node.js removed both the warning and the plans for making the change in 7.x :smile:

Problem solved! 😸

**Comment by paleite** [comment] 2016-12-09 23:46
That's what I call effective problem solving! :)
