### ISSUE TITLE
Cannot use QueryFiles inside transactions.

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [vitaly-t/pg-promise#531] opened 2018-07-25 21:59 UTC
### Expected behavior
`test.sql`
```sql
CREATE TABLE IF NOT EXISTS ${schema^}.test;
```
`index.js`
```javascript
const qf = new QueryFile("./test.sql", params: { schema: "myschema" })
this.pgp.tx(async (tx) => {
  await tx.none(qf)
})
```
Should execute the QueryFile.
### Actual behavior
An `invalid query format` error is thrown.
### Steps to reproduce
1. Create a QueryFile object
2. Inside of a transaction, attempt to execute a query using that QueryFile

### Environment

* Version of pg-promise: 8.4.5
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 8.11.3

**Comment by vitaly-t** [comment] 2018-07-26 01:36
I cannot reproduce the error.

For starters, what you are showing passed as options into the QueryFile isn't even a valid syntax.

And your `CREATE TABLE` SQL is invalid, as you are trying to create a table without fields, which in itslef would throw an error.

But none of them will throw the error you're describing. Something else is wrong in your code, and you need to find out what else you are may be doing wrong there.

**Comment by vitaly-t** [comment] 2018-07-27 16:56
Closing due to non-response, and as being non-reproducible.

**Closed by vitaly-t** 2018-07-27 16:56 UTC
Labels: requires feedback
