### ISSUE TITLE
CSV filter not treating Buffer (bytea) correctly

### ISSUE THREAD

**Issue by moltco** [vitaly-t/pg-promise#891] opened 2023-10-05 11:00 UTC
### Expected behavior
When **CSV filter** is used to transform object to variables `Buffer`s are not correctly translated, eg:

`INSERT INTO $1:alias($2:name) VALUES($2:csv) RETURNING *`

If the object specified as $2:csv contains a `Buffer` (e.g. hashed password) that corresponds to `bytea` in Posgres, the CSV filter converts Buffer to a plain string. 

This is problematic as Buffer is likely to contain Unicode characters, so the CSV filter should a) mark the string with "E" and also escape any \u0000 as posgres doesn't like unicode and null in strings. I think the CSV filter should test anything that it converts into string if it contains unicode and should mark with E etc. I guess instead of hashed password I could have user input with unicode character (e.g. non-latin characters) which would not be marked with E and (I guess) would fail when insert is made.

This issue has been discussed at length here (https://github.com/brianc/node-postgres/issues/1115)

### Actual behavior
Plain string is created from Buffer, without unicode marking ("E") and without escaping \u0000

### Steps to reproduce
see  (https://github.com/brianc/node-postgres/issues/1115)

### Environment

* Version of pg-promise: 11.5.4
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 18.8

**Comment by vitaly-t** [comment] 2023-10-05 12:36
Sounds like perhaps you are not passing parameters correctly. Please include a reproducible code example here.

**Comment by moltco** [comment] 2023-10-06 13:51
You are partially correct, I was doing Buffer.from("abc").toString() with the $2:csv filter which has caused issues. If I do just Buffer.from("abc") this appears to be working. But the unicode null \u0000 definitely breaks the code and also I can't see any unicode string encapsulation when query is created (ie no E'abc').

Here is a code that will fail:

```
var obj = {
          id: crypto.randomUUID(), // ignore this - I need some fields for referential integrity/constratints
          org_id: id_org, // ignore 
          password: Buffer.from("test"), // ignore
          salt: Buffer.from("salt"), // ignore
          firstName: "Peter",  // ignore 
          lastName: '\uD83D\uDC04\u0000', // <- this fails
          email: 'test@example.com' // ignore
        }

        const q = sql('generic/create.sql'); // INSERT INTO $1:alias($2:name) VALUES($2:csv) RETURNING *
        const insertResult = await db.one(q, ['users', obj]);
        console.log(JSON.stringify(insertResult));
```

With the above code I get error code is 08P01 on the lastName field. 

If I change \u0000 to something else, e.g. \u0001 this works. However, when inspecting the text of the compiled query - there is no escaping for unicode characters or marking the string as unicode, e.g.E'\uD83D\uDC04\u0000' - I am not sure if this would improve things or not though but could be a prudent thing to do. I read on the interweb that for \u0000 to be passed to Postgress one needs more escaping so perhaps it's a special case that should be treated as such?

Here is the full error stack
```
invalid message format

INSERT INTO users("id","org_id","password","salt","firstName","lastName","email") VALUES('aa03c249-e82b-4e24-a759-29771d6e10d9','8e9ee4b1-65a1-464e-9d63-c67c29953fda','\x74657374','\x73616c74','Peter','🐄','test@example.com') RETURNING *

error: invalid message format
    at Parser.parseErrorMessage (C:\Users\m\source\repos\id\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (C:\Users\m\source\repos\id\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (C:\Users\m\source\repos\id\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (C:\Users\m\source\repos\id\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (C:\Users\m\source\repos\id\lib\events.js:517:28)
    at Socket.emit (C:\Users\m\source\repos\id\lib\domain.js:489:12)
    at addChunk (C:\Users\m\source\repos\id\lib\internal\streams\readable.js:335:12)
    at readableAddChunk (C:\Users\m\source\repos\id\lib\internal\streams\readable.js:308:9)
    at Socket.Readable.push (C:\Users\m\source\repos\id\lib\internal\streams\readable.js:245:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {length: 143, name: 'error', severity: 'ERROR', code: '08P01', detail: undefined, …}

```

**Comment by vitaly-t** [comment] 2023-10-08 05:13
You can provide your own solution to the issue, via [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting), by escaping it as you want.

**Comment by moltco** [comment] 2023-10-08 06:15
Thanks for the tip I did consider CTFs (and use them for more complex types). 

I was hoping that this issue would be recognized as a bug/issue and a patch would go into the pg-promise. The \u0000 in a string is a valid string (albeit an edge case) for javascript so, ideally, I shouldn't have to create a workaround for the pg-promise, it should 'just work'.

**Comment by vitaly-t** [comment] 2023-10-08 06:39
[The original issue](https://github.com/brianc/node-postgres/issues/1115) was never resolved, and I do not see what solution, if any, is possible inside this library. Most likely, this needs to be addressed inside the base driver, and not here.

**Comment by vitaly-t** [comment] 2023-10-12 08:23
I am closing it, because I'm not planning to do any fixes on this end, it is down to the base driver, as per the old linked issue.

**Closed by vitaly-t** 2023-10-12 08:23 UTC
Labels: no-issue, dependency issue
