### ISSUE TITLE
Unable to execute a query with :name filter as it is adding double quotes.

### ISSUE THREAD

**Issue by shivammalhotraone** [vitaly-t/pg-promise#619] opened 2019-06-17 09:55 UTC
### Query
`db.any('SELECT $1~ FROM food_menu_item AS fmi ORDER BY $2~ OFFSET $3 FETCH FIRST $4 ROW ONLY', [ ['fmi.id', 'fmi.title', 'fmi.description'], 'fmi.id', 0, 10]);`

### Actual Output
Double quotes are getting added whenever I use :name filter. I get an error "fmi.id" column not defined when I run the query.
`SELECT "fmi.id", "fmi.title", "fmi.description" FROM food_menu_item AS fmi ORDER BY "fmi.id" OFFSET 0 FETCH FIRST 10 ROW ONLY`

### Expected Output
The query executes successfully without any quotes.
`SELECT fmi.id, fmi.title, fmi.description FROM food_menu_item AS fmi ORDER BY fmi.id OFFSET 0 FETCH FIRST 10 ROW ONLY`

### Environment
* Version of pg-promise: ^8.6.5
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.16.0

**Comment by vitaly-t** [comment] 2019-06-17 15:18
Duplicate of #606.

**Closed by vitaly-t** 2019-06-17 15:18 UTC
Labels: duplicate, invalid usage
