### ISSUE TITLE
quoted string with $ used with update helper

### ISSUE THREAD

**Issue by chougron** [vitaly-t/pg-promise#727] opened 2020-05-24 14:56 UTC
### Expected behavior

Object should be updated in the database with no issue.

### Actual behavior

An error is thrown : `Variable $2 out of range. Parameters array length: 1`

### Steps to reproduce
I have a function to insert or update objects in my database. Basically if the object I give contains an id, I make an update, otherwise an insert.
I use the **insert** and **update** functions of the helper to help me build the queries. I found out today that everything is working fine for the insert, but for the update, if one of the values contains a $ like for the prepared queries, it is not working.
Here is a little example of something that will fail :

```js
const data = {
    id: '123123123',
    firstname: 'test',
    password: '$2b$15$0sCsSeK5kDwQs6gXqBS5UO85GSCfHQ01X2RwIYGqBwJi4IW47rqkC'
};
return await database.one<T>(
    pgPromise.helpers.update(data, null, table) +
        ' WHERE "id" = $1 RETURNING *',
    [data.id],
);
```

I saw that a similar problem was solved a long time ago in issue #27 , and it is working as it should with the insert helper, so I believe it must be a bug.

I tried to check where the problem was coming from and here is the query called in **formatAs.array** :

`
update "user" set "id"='e887001c-1371-453d-8663-52bb9ca22195',"email"='regist@test.com',"password"='$2b$15$0sCsSeK5kDwQs6gXqBS5UO85GSCfHQ01X2RwIYGqBwJi4IW47rqkC',"firstname"='Regis',"lastname"='Test',"dateOfBirth"='2002-01-01',"createdAt"='2020-05-11T21:23:22.814+02:00',"updatedAt"='2020-05-24T16:31:39.786+02:00',"isDeleted"=false,"deletedAt"=null WHERE "id" = $1 RETURNING *
`

Sadly, in this place the variables to replace are found by the multipleValues regex pattern, and I do not dare to change that, as it must definitely be used in other parts.

### Environment

* Version of pg-promise: 10.5.0
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 10.15.3

**Comment by vitaly-t** [comment] 2020-05-24 17:39
Duplicate of #443, and many others - double query formatting.

**Closed** 2020-05-24 21:49 UTC
Labels: duplicate, invalid usage
