### ISSUE TITLE
Crash on connection reset

### ISSUE THREAD

**Issue by resure** [vitaly-t/pg-promise#438] opened 2017-12-25 16:06 UTC
I've encountered an unhandled error on one of my production servers that was caused by pg-promise after connection to database was terminated. Termination itself was expected (it was caused by bad network conditions in datacenter), but this exact error is not looking like somehting normal.

```
error=Error: Connection terminated
    at Client.<anonymous> (/opt/app/node_modules/pg/lib/client.js:210:17)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Connection.emit (events.js:207:7)
    at TLSSocket.<anonymous> (/opt/app/node_modules/pg/lib/connection.js:138:10)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

```
TypeError: Cannot read property 'options' of undefined
    at BoundPool.onError (/opt/app/node_modules/pg-promise/lib/database.js:1310:25)
    at emitTwo (events.js:125:13)
    at BoundPool.emit (events.js:213:7)
    at BoundPool.<anonymous> (/opt/app/node_modules/pg-pool/index.js:93:10)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at Client.<anonymous> (/opt/app/node_modules/pg/lib/client.js:199:19)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at TLSSocket.<anonymous> (/opt/app/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

----
```
    "pg-promise": {
      "version": "6.3.5",
      "resolved": "...",
      "integrity": "...",
      "requires": {
        "manakin": "0.4.7",
        "pg": "6.4.1",
        "pg-minify": "0.4.2",
        "spex": "1.2.0"
      }
    },
```

**Comment by vitaly-t** [comment] 2017-12-25 16:29
Duplicate of #396

**Closed** 2017-12-25 23:28 UTC
Labels: duplicate
