### ISSUE TITLE
Make pg-native a peer dependency.

### ISSUE THREAD

**Issue by flovilmart** [vitaly-t/pg-promise#490] opened 2018-03-10 21:13 UTC
Hi there, the pg-native dependency is breaking with the latest parse-server (https://github.com/parse-community/parse-server/issues/4625)

Is it possible to make this dependency a peer dependency or an optional one?

Thanks!

**Comment by vitaly-t** [comment] 2018-03-10 21:20
Duplicate of #488

**Closed by vitaly-t** 2018-03-10 21:20 UTC
Labels: duplicate
