### ISSUE TITLE
comma problem, whith pgp.as.csv join

### ISSUE THREAD

**Issue by flavioprado** [vitaly-t/pg-promise#501] opened 2018-04-05 15:20 UTC
Hi Vitaly,

The problem of Issue https://github.com/vitaly-t/pg-promise/issues/106
 is occurring again with pg-promisse versions above 7.3.4

This is my code:

```js
insertAtomic(file: any): Promise<any> {
       
        let insertStatement = 'INSERT INTO $[schemaName~].$[tableName~]($[columns^]) VALUES($[values^])';

        return this.db.tx(t => {

            return t.one(insertStatement + ' returning ger_idfile', {
                schemaName: this.schemaName,
                tableName: this.tableName,
                columns: columnsFiles.map(this.pgp.as.name).join(),
                values: valuesFiles.map(this.pgp.as.csv).join()
            }).then(result => {
                let queries = [];

                let columnsFiles: Array<string> = [
                    'ger_id',
                    'arq_file'
                ];
                let valuesFiles = [
                    file_id,
                    file
                ];

                queries.push(t.any(insertStatement, {
                    schemaName: this.schemaName,
                    tableName: 'tb_files',
                    columns: columnsFiles.map(this.pgp.as.name).join(),
                    values: valuesFiles.map(this.pgp.as.csv).join()
                }));

                let source = (index, data, delay) => {
                    return queries[index];
                };

                return t.sequence(source);
            });
        });
    }
```

the Buffer file  in valueFiles.map  is being filled with commas, in version 5.3.4
the problem does not occur

Expected output:
pgp.as.csv(buf) '\x010203'

Actual output:
pgp.as.csv(buf) 1,2,3

* Version of pg-promise: 7.3.4 or upper
* OS type Linux/Windows/Mac: Ubuntu Linux 
* Version of Node.js: v8.9.1

**Comment by vitaly-t** [comment] 2018-04-05 15:37
Please format the code further on. I have done it for the question there.

For such an issue you need to provide:

* Expected query syntax
* Generated query syntax

Also, which of the parameters gives you the problem?

And it is pointless using syntax like `columns: columnsFiles.map(this.pgp.as.name).join(),`. Instead, you can just do `columns:name` in the template, which will be injected automatically.

**Comment by vitaly-t** [comment] 2018-04-05 20:01
Slightly changed code should rectify the immediate issue:

```js
function insertAtomic(file: any): Promise<any> {

    let insertStatement = 'INSERT INTO $[schema:name].$[table:name]($[columns:name]) VALUES($[values:csv])';

    return this.db.tx(t => {

        return t.one(insertStatement + ' RETURNING ger_idfile', {
            schema: this.schemaName,
            table: this.tableName,
            columns: columnsFiles,
            values: valuesFiles
        }).then(result => {
            let queries = [];

            let columnsFiles: Array<string> = [
                'ger_id',
                'arq_file'
            ];
            let valuesFiles = [
                file_id,
                file
            ];
            
            queries.push(t.none(insertStatement, {
                schema: this.schemaName,
                table: 'tb_files',
                columns: columnsFiles,
                values: valuesFiles
            }));

            let source = (index, data, delay) => {
                return queries[index];
            };

            return t.sequence(source);
        });
    });
}
```

I don't know why you were trying to use the CSV formatting for each individual value, hence the problem, it seems. The CSV should be used for the entire array of parameters, and that's it.

And I changed it to the automatic syntax, for simplicity.

Other than that, I do not understand why you are using `sequence` to execute a single query there. I understand if you removed some code there for simpicity, because the way the example is, it makes no sense.

**Comment by vitaly-t** [comment] 2018-04-06 16:10
From the lack of responses, I conclude the issue is no longer of interest, so I'm closing it.

**Closed by vitaly-t** 2018-04-06 16:10 UTC
Labels: question
