### ISSUE TITLE
ColumnSet explicit type casting issue on multiple update

### ISSUE THREAD

**Issue by fend25** [vitaly-t/pg-promise#272] opened 2017-01-27 11:27 UTC
Good day everyone!
I encountered a problem:
When I try to execute `pgp.helpers.update` query with empty array, it fails due to not casting in values part of the query
```js
const fields = ['?id', {name: 'intarr', cast: 'int[]'}]
const cs = new pgp.helpers.ColumnSet(fields, {table: 'test1'})
const data = {id: 1, intarr: []}
const query = pgp.helpers.update(data, cs) + ` WHERE v.id = t.id`
```
and it generates such sql:
```sql
 update "test1" as t set "intarr"=v."intarr"::int[] from (values(1, array[])) as v("id", "intarr") WHERE v.id = t.id
-- there is an empty array without casting -------------------------------^
```
and pg throws such error: `cannot determine type of empty array`

---

example table 
```sql
CREATE TABLE test1 (id int4, intarr int4[]);
INSERT INTO test1 (id, intarr) VALUES (1, NULL);
```

**Comment by vitaly-t** [comment] 2017-01-27 11:37
Wow! This look like a bug in PostgreSQL...

It is supposed to understand the old/string array notation of `{1,2,3}` and the new one of `array[1,2,3]` in the exact same way, but in this particular example it fails.

i.e. if instead of passing in `array[]` we pass in `'{}'`, which is the old presentation of an empty array, it succeeds. This doesn't make sense.

**Comment by vitaly-t** [comment] 2017-01-27 12:24
I've asked about it on StackOverflow: [PostgreSQL fails on empty constructor arrays](http://stackoverflow.com/questions/41893444/postgresql-fails-on-empty-constructor-arrays).

And following the answers, I can see that the issue is as follows...

The forward-casting within multi-row updates doesn't really work, or maybe it works sometimes, but not consistently...

The solution is to change from the forward type casting to in-line type casting within the library.

**Comment by vitaly-t** [comment] 2017-01-27 14:31
Fixed in [v.5.5.3](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.5.3)

**Closed by vitaly-t** 2017-01-27 14:31 UTC
Labels: bug
