### ISSUE TITLE
«WARNING: Creating a duplicate database object for the same connection» depends on the location of the JS file

### ISSUE THREAD

**Issue by SakhnoA** [vitaly-t/pg-promise#769] opened 2020-12-28 15:44 UTC
### Expected behavior
The same behavior of pg-promise when placing js in different folders

### Actual behavior
When you change the location of the plug-in js file, a warning appears:

> WARNING: Creating a duplicate database object for the same connection.
>     at Object.<anonymous> (D:\Projects\djivi3\djivi3_only_tw\Server\db.js:18:12)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

### Steps to reproduce
Folder structure:
..
+ assets 
   - testAssets.js
+ Server 
    + controllers
          - goods.controller.js
    + libs 
          - testServer.js
     - db.js 

testAssets.js and testServer.js  have the same code (taking into account the location of the db.js):

testServer.js
```
const {db} = require("../Server/db");
class Test {
  constructor() {
    this.prop1 = 1;
  }
}
module.exports = Test;
```

testAsset.js
```
const {db} = require("../db.js");
class Test2 {
  constructor() {
    this.prop1 = 1;
  }
}
module.exports = Test2;
```

**If text of goods.controller.js:**
```
const {db} = require("../db.js");
let ProductServer = require("../../assets/productServer.js")
const Test = require('../libs/testServer')
// const Test2 = require('../../assets/testAssets')
```
**everything is OK**

but if:
```
const {db} = require("../db.js");
let ProductServer = require("../../assets/productServer.js")
// const Test = require('../libs/testServer')
const Test2 = require('../../assets/testAssets')
```
**There is a warning:**
> WARNING: Creating a duplicate database object for the same connection.
>     at Object.<anonymous> (D:\Projects\djivi3\djivi3_only_tw\Server\db.js:18:12)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

That is, the classes differ only in location, and the consequences are different.
 I can't figure out how to defeat this error so that js is in the "assets" folder.

### Environment

* Version of pg-promise: 10.7.0
* OS type (Linux/Windows/Mac): Win 10
* Version of Node.js: 12.18.3

**Comment by vitaly-t** [comment] 2020-12-28 16:57
What is your implementation for `../Server/db` and `../db.js`?

**Comment by SakhnoA** [comment] 2020-12-28 18:36
Server/db.js:

```
const pgp = require("pg-promise")({});
// pgp.pg.types.setTypeParser(20, BigInt);

const keys = require("./keys");
const db = pgp(keys.PG_URI);

module.exports = {db}
```

As I understand I don't re-create it. I'm only trying to use: require("../db.js");


May be something here: 
Console data when server start:

> Debugger attached.
> [nodemon] 2.0.4
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): server\**\*
> [nodemon] watching extensions: js,mjs,json
> [nodemon] starting `node server/indexOnlyServer.js`


Perhaps this behavior occurs due to the fact that  
 *\assets\testAssets.js 
is out of
 server \ *   ?

**Comment by vitaly-t** [comment] 2020-12-28 20:47
I cannot reproduce the issue with the code that you provided. In fact, this issue was logged before, and was never reproducible, it was always a problem on the client side somewhere.

So I can only suggest that you try to diagnose it on your side, in every place where you are creating a database object, somewhere it is obviously called twice.

**Comment by SakhnoA** [comment] 2020-12-29 06:16
Sever/db.js  is the only place in the project where i create a database object.

At the same time, I run only the server part and get this warning.

My experiments have shown that only transferring a JS file to the directory (.../Server/) helps.
So far, I did this - I moved the real JS to the directory ...Server/libs/ 

Thank you for your concern and time

**Comment by vitaly-t** [comment] 2020-12-29 12:02
I don't know if it is something to do with `nodemon` or else. But if you can give me actually reproducible example, only then I can look into that closer.

**Comment by SakhnoA** [comment] 2020-12-29 12:32
If you are interested, I will clean the project and provide it for your examination?
For future generations )

**Comment by vitaly-t** [comment] 2020-12-29 12:49
Ok :)

**Comment by vitaly-t** [comment] 2020-12-31 14:15
Ok, since you didn't provide the example in the end, I am closing the issue for now. Let me know if you have an update.

**Closed by vitaly-t** 2020-12-31 14:15 UTC
Labels: needs clarification
