### ISSUE TITLE
pg-promise error “Promise library must be specified

### ISSUE THREAD

**Issue by nikunjsobhashana** [vitaly-t/pg-promise#174] opened 2016-06-29 11:46 UTC
While i am using pg-promise library with node.js 0.10 this error occure

**Comment by vitaly-t** [comment] 2016-06-29 12:09
Duplicate of http://stackoverflow.com/questions/37566944/how-to-fix-pg-promise-error-promise-library-must-be-specified

**Closed by vitaly-t** 2016-06-29 12:09 UTC
