### ISSUE TITLE
Error on escape character '$'

### ISSUE THREAD

**Issue by 4321ip** [vitaly-t/pg-promise#683] opened 2019-12-14 18:50 UTC
### Expected behavior
update should executed normally

### Actual behavior
`"Unhandled Rejection at Promise! RangeError: Variable $1000 out of range. Parameters array length: 1\nstack: \nRangeError: Variable $1000 out of range. Parameters array length: 1\n    at /Users/igor/dev/api/node_modules/pg-promise/lib/formatting.js:188:19\n    at RegExp.[Symbol.replace] (<anonymous>)\n    at String.replace (<anonymous>)\n    at Object.array (/Users/igor/dev/api/node_modules/pg-promise/lib/formatting.js:172:22)\n    at Object.formatQuery (/Users/igor/dev/api/node_modules/pg-promise/lib/formatting.js:296:29)\n    at Database.$query (/Users/igor/dev/api/node_modules/pg-promise/lib/query.js:129:40)\n    at Database.<anonymous> (/Users/igor/dev/api/node_modules/pg-promise/lib/query.js:263:23)\n    at /Users/igor/dev/api/node_modules/pg-promise/lib/database.js:329:42\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)\nFrom previous event:\n    at Database.query (/Users/igor/dev/api/node_modules/pg-promise/lib/database.js:327:14)\n    at Database.none (/Users/igor/dev/api/node_modules/pg-promise/lib/database.js:506:30)\n    at _callee6$ (/Users/igor/dev/api/src/db/postgres/index.js:283:12)\n    at tryCatch (/Users/igor/dev/api/node_modules/regenerator-runtime/runtime.js:45:40)\n    at Generator.invoke [as _invoke] (/Users/igor/dev/api/node_modules/regenerator-runtime/runtime.js:271:22)\n    at Generator.prototype.<computed> [as next] (/Users/igor/dev/api/node_modules/regenerator-runtime/runtime.js:97:21)\n    at tryCatch (/Users/igor/dev/api/node_modules/regenerator-runtime/runtime.js:45:40)\n    at invoke (/Users/igor/dev/api/node_modules/regenerator-runtime/runtime.js:135:20)\n    at /Users/igor/dev/api/node_modules/regenerator-runtime/runtime.js:145:13" 
`
### Steps to reproduce

```js
let dataValue = {
    field: 'price $1000'
  }
  **await db.none(`insert into service.table_test (data) values ($1)`, [dataValue])**
  console.debug('**OK**')
  **await db.none(`update service.table_test set data = $1 where $2 = $2`, [dataValue, 123456])**
  console.debug('**OK**')
  let table = new pgp.helpers.TableName({ table: 'table_test', schema: 'service' })
  let updateData = { data: dataValue }
  let csData = Object.keys(updateData).map(field => {
    return { name: field, cast: 'jsonb' }
  })
  if (csData.length === 0) return
  const cs = new pgp.helpers.ColumnSet(csData)
  **await db.none(`${pgp.helpers.update(updateData, cs, table)}`)**
  console.debug('**OK**')

  **await db.none(`${pgp.helpers.update(updateData, cs, table)} WHERE $1=$1`, [12345])**
  console.debug('**_NOT OK!!!!_** ') // "Unhandled Rejection at Promise! RangeError: Variable $1000 out of range....
```

### Environment

* Version of pg-promise: 10.3.1
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 13.2

**Comment by vitaly-t** [comment] 2019-12-14 21:41
Duplicate of #443. Cause: Double-formatting values.

In the line below you format all values first, via `helpers.update`, and then re-format them again through the query method, hence the error.

```js
await db.none(`${pgp.helpers.update(updateData, cs, table)} WHERE $1=$1`, [12345])
```

The condition part in such cases needs to be formatted separately, and then amended:

```js
const where = pgp.as.format('WHERE $1 = $1', [12345]);
await db.none(`${pgp.helpers.update(updateData, cs, table)} ${where}`);
```

**Closed by vitaly-t** 2019-12-14 21:41 UTC
Labels: duplicate, invalid usage
