### ISSUE TITLE
Node 14.1.0: Cannot find module 'pg-connection-string'

### ISSUE THREAD

**Issue by tobiasmuehl** [vitaly-t/pg-promise#721] opened 2020-05-04 10:02 UTC
### Expected behavior
Can import and use PgPromise normally

### Actual behavior
Import fails

### Steps to reproduce
Node 13 works: https://runkit.com/mm2/14/2.0.0
Node 14 fails: https://runkit.com/mm2/14/1.0.0

### Environment

* Version of pg-promise: 10.5.2
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 14.1.0

**Comment by vitaly-t** [comment] 2020-05-04 10:12
I am using Node v14.1.0 here, I have done fresh installation of pg-promise, and still cannot reproduce the issue you described. There must be something else specific in your project.

**Comment by vitaly-t** [comment] 2020-05-04 10:26
Also, the link you provide for Node 13 points at a test that fails the same way.

**Comment by vitaly-t** [comment] 2020-05-05 10:44
@tobiasmuehl If you can't provide additional details, I will have to close it as non-reproducible.

**Comment by vitaly-t** [comment] 2020-05-06 07:41
Closing, as non-reproducible, and due to non-response.

**Closed by vitaly-t** 2020-05-06 07:41 UTC
Labels: requires feedback

**Comment by tobiasmuehl** [comment] 2020-05-06 08:00
Weird, when I opened the issue the v13 link worked and the v14 link didn't, now both don't work. On my local machine v14.2.0 (updated again from 14.1.0) continues to not work without an error message, but I believe the problem originates in the upstream `pg` dependency. Just staying on v13 for now and assuming it will be fixed soon anyways

**Comment by vitaly-t** [comment] 2020-05-06 08:26
Have you tried fresh install? - by deleting `node_modules` folder and then reinstalling everything?

It is worth trying.

**Comment by tobiasmuehl** [comment] 2020-05-06 09:06
yes, didn't fix it. It's noteworthy that on my machine there is no error at all, the script simply exits immediately (exit code 0)

**Comment by vitaly-t** [comment] 2020-05-06 09:32
Then it is worth debugging to find out the exact problem.

**Comment by mrkirchner** [comment] 2020-05-18 22:44
Seeing similar issue, running a docker container from node:alpine which is using node 14.2.0

App would just exit silently with no errors.  Glad i saw this issue, switched docker to node:alpine-lts (aka 12.16.3) everything works again.  If i get some free time ill try to upgrade my local docker to 14 and debug to see if i can find the error.

**Comment by vitaly-t** [comment] 2020-05-18 23:23
@mrkirchner Are you using the latest v10.5.6 of the library?

**Comment by mrkirchner** [comment] 2020-05-18 23:34
Just checked was using v10.5.1 upgraded to v10.5.6 and it seems like its all working again.  Thanks for responding so quickly.
