### ISSUE TITLE
error: there is no parameter $10000

### ISSUE THREAD

**Issue by MagnumDopus** [vitaly-t/pg-promise#258] opened 2016-12-22 21:06 UTC
Seems I have hit some sort of hard limit in pg-promise.

I am attempting to do a massive insert within a single query (maybe this is bad practice?).

I have verified that both the query string is valid and that the parameter array I am passing is also correct but it throws this error: 

{ error: there is no parameter $10000
    at Connection.parseE (/Users/kevinhunt/Sites/DE2/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/kevinhunt/Sites/DE2/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/kevinhunt/Sites/DE2/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'error',
  length: 102,
  severity: 'ERROR',
  code: '42P02',
  detail: undefined,
  hint: undefined,
  position: '266024',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_expr.c',
  line: '827',
  routine: 'transformParamRef' }

However both my query string contains the $10000 parameter and my paramater array contains a valid value at that location in the array.  If I limit the insert to be less than 10000 parameters it executes without error.  

This can easily be duplicated by attempting a large insert I would imagnie (>10000)

**Comment by vitaly-t** [comment] 2016-12-27 12:50
it is the wrong approach. i will detail when back from holidays.

**Comment by vitaly-t** [comment] 2016-12-30 23:45
Duplicate of #143

**Closed by vitaly-t** 2016-12-30 23:45 UTC
