### ISSUE TITLE
Question re: WARNING: Creating a duplicate database object for the same connection

### ISSUE THREAD

**Issue by CalebEverett** [vitaly-t/pg-promise#175] opened 2016-06-29 18:46 UTC
Is the right way to set this up in an Express app to create a separate db module per the [example](http://vitaly-t.github.io/pg-promise/Database.html) and then require that in each set of routes? I've done that, but am still getting the warnings. Do I need a separate database object for each set of routes or can you recommend otherwise? Thanks,

**Comment by vitaly-t** [comment] 2016-06-29 18:56
You should create a single database object per connection details, and then reuse it.

From the [start-up instructions](https://github.com/vitaly-t/pg-promise#database):

>You should create only one global/shared db object per connection details.

**Comment by vitaly-t** [comment] 2016-06-29 18:57
See related questions:

* http://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise
* http://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app

**Comment by vitaly-t** [comment] 2016-06-29 19:21
Oh, and complete forgot: [WARNING: Creating a duplicate database object for the same connection.](https://github.com/vitaly-t/pg-promise/wiki/FAQ#warning-creating-a-duplicate-database-object-for-the-same-connection)

That should do it :smile:

**Comment by CalebEverett** [comment] 2016-06-29 20:56
I was going off of those, but missed a module I was pulling into one of my route files. Thanks again

**Comment by vitaly-t** [comment] 2016-06-30 12:02
@CalebEverett 

See the changes brought with [v.5.1.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.1.0)

**Comment by thenikso** [comment] 2017-01-11 16:50
I've a followup on this. I'm using pg-promise both in my app and on an integration test wrapper that initialize the test database to then import and call the app.

I get this warning which I believe it's not a problem and I can safely ignore it. However do you have any further best practice regarding this kind of scenarios?

**Comment by vitaly-t** [comment] 2017-01-11 17:07
So, your intergration test and the application are using separate configurators for the database, while connecting to the same database. Is it really necessary? Why not place it in a shared module?

**Comment by MitMaro** [comment] 2017-01-11 19:29
We have a distributed microservice like system, that sometimes runs several independant services within the same node process, with an unknown set of database connections. This meant that explicitly using a shared module wasn't a viable solution. Instead we ended up creating a factory that would use a hash of the configuration to return a cached instance. Looks something like this:

```javascript
const pgPromise = require('pg-promise');
const cache = new Map();
module.exports = function  databaseConfig) {
	const dbKey = JSON.stringify(databaseConfig, Object.keys(databaseConfig).sort());
	if (cache.has(dbKey)) {
		return cache.get(dbKey);
	}
	const instance = pgPromise(databaseConfig);
	cache.set(dbKey, instance);
	return instance;
};
```

**Comment by vitaly-t** [comment] 2017-01-11 19:35
@MitMaro is this module supposed to return an initialized `pgp` variable or a new `db` instance?

If it is the former, it is fine, if it is the latter - it won't work, because the library's initialization call is missing, i.e. `var pgp = require('pg-promise')(/*initialization options*/)`, not just `var pgp = require('pg-promise')`.

**Comment by MitMaro** [comment] 2017-01-11 20:17
I made a mistake when I pulled out the example from the codebase. It's a database connection, not the pg-promise instance. Our actual code is a bit more complex. I've edited the example.

I was initially suppressing the warning but wanted to use a shared connection pool when possible. I didn't think to check to see if pg-promise reused an existing connection pool on the same connection parameters, but my guess is that it does not.

**Comment by vitaly-t** [comment] 2017-01-11 20:19
pg-promise uses just one connection pool, as per `node-postgres` v5.1

**Comment by MitMaro** [comment] 2017-01-11 20:41
Interesting. I think I found a bug in either pg-promise or node-postgres then. I will do up a test case and report it.

**Comment by benoittgt** [comment] 2017-01-13 16:53
Thanks a lot with your comment I just discover : http://vitaly-t.github.io/pg-promise/txMode.TransactionMode.html

> this is designed to be called more than once:
But this handler is called only once (in my case every 4 min)

Thanks again

**Comment by vitaly-t** [comment] 2017-01-13 16:54
> in my case every 4 min

that's not only once :)

**Comment by vitaly-t** [comment] 2017-01-13 17:03
@benoittgt see this: http://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise

**Comment by lakesare** [comment] 2017-03-29 17:02
these winky emojies are awful, I can't think of anything more pseudo-friendly and condescending.

**Comment by vitaly-t** [comment] 2017-03-29 18:25
@lakesare what is this all about?

**Comment by RomeHein** [comment] 2018-11-04 13:03
Hello!
I'm currently trying to implement authentification on my API. I was wondering how could I manage different user connections to the db?
This is how I currently create the connection:
```
const pgp = require('pg-promise')();

let instance = null;

module.exports = class Connector {

  constructor(user,psw) {

    if (!instance || (user && psw)) {
      instance = this;

      this.config = {
        user: user || process.env.boUser,
        database:process.env.boDatabase, 
        password: psw || process.env.boUserPassword, 
        host:process.env.boHost, 
        port:process.env.boPort,
      };
    
      this.db = pgp(this.config);
    }

    return instance;
  }

}
```

And I use it like so (Connector is a global variable):

```
module.exports = class Pack {
    ...
    static all() {
        return Connector.db.tx(t => {
            return t.batch([t.manyOrNone(sql.pack.findAll)]);
        })
        .then(data => {
            if (data[0].constructor === Array && data[0].length > 0) {
                return Pack.parseArray(data[0]);
            }
            return null;
        });
    }
}
```

I'm a bit lost and don't get how I can create multiple connections.
Let's say my API receive 10 requests from 10 different users, with different rights access on the db, how can I manage that on the API side?
I feel like my pattern is not right.

**Comment by vitaly-t** [comment] 2018-11-04 16:14
@RomeHein You would have to create and keep a separate `db` object, but that's not a great idea, because if it is the same server, the valuable IO connections would be consumed, and not reused across users.

**Comment by RomeHein** [comment] 2018-11-04 18:46
Ok thanks for your quick answer!
I'll move the authentification logic to the API, and keep only one user to perform the IO connections to the db.
Thx again

**Comment by oliversalzburg** [comment] 2019-06-03 21:24
@vitaly-t Is there a way to suppress the warning?

I'm encountering this during automated testing. I have a primary connection in application code and I'm establishing another connection with identical parameters in my test code. I manipulate the database through the test connection to set up state, then run my test which causes application code to mutate the database state through the primary connection, then assert state through the test connection.

I explicitly do not want to share the database connection between application and test context. I have no particular reason for this other than trying to keep both contexts separate from each other. I felt like that is just cleaner and a better approach.

Please let me know your thoughts on this. Thanks

**Comment by vitaly-t** [comment] 2019-06-03 21:28
@oliversalzburg [Initialization option `noWarnings` can switch the warning off](http://vitaly-t.github.io/pg-promise/module-pg-promise.html).

**Comment by ild-dsv** [comment] 2019-06-19 12:21
Hi @vitaly-t,

After reading through pg-promise's official document and your explanations on StackOverflow as well, when we're working with pg-promise with Stack:
- AWS Lambda
- Serverless-offline (or on production)
- Serverless-webpack
I still get this warning ```WARNING: Creating a duplicate database object for the same connection.```

My approach:
Only create data object once then import to lambda function when interactive with database (Our database is using PostgreSQL)

How to reproduce:
utils/db.js
```javascript
import pgPromise from 'pg-promise'
import Promise from 'bluebird'
import pgPromise from 'pg-promise'
const initOptions = {
  promiseLib: Promise,
  // noWarnings: true,
  capSQL: true,
}
const pgp = pgPromise(initOptions)

const dbObject = pgp(process.env.DATABASE_URL)

function disconnect(db) {
  return db ? db.$pool.end() : null
}

export { dbObject, disconnect }
```

lambaFunc.js

```javascript
import { dbObject, disconnect } from './utils/db'

export const handler = async (event, context) => {
  if (event.source === 'serverless-plugin-warmup') {
    return 'Lambda is warm!'
  }

  const dbClient = dbObject

  const response = {
    statusCode: 200,
  }
 // we can do something with dbClient, however, even I don't do anything, just do like this, it also throws the warning
  disconnect(dbClient)
  
  return response
}

```

Do you have any idea about this?

Is it possible because of serverless-webpack?

**Comment by vitaly-t** [comment] 2019-06-19 12:54
@ild-dsv All I can say is that somehow, somewhere you are creating a duplicate database object. I do not personally use Lambda, but I hear there is a lot of connection-related problems with it.

You can always debug it yourself - hack the library code and make it throw an error with stack upon a second call, to show where the second call is coming from.

**Comment by ild-dsv** [comment] 2019-06-21 17:23
@ild-dsv, thanks for your suggestion. It's really useful for me to track this warning. Basically, I think the main error of my case, it can come from the serverless-webpack plugins. It freshly forces reinitializing our dbObject during the compiling time. I tried to use dynamic import to avoid this. However, for my case, It needs a little help with new implements from serverless-webpack.

Anyway, I really like pg-promise and also give a thumb up for your help. Thank you. @vitaly-t

**Comment by LRagji** [comment] 2020-01-30 15:45
@vitaly-t  Thanks for this package its really awesome, just a follow up Q on this warning part, it this warning now an anti-pattern? cause as per latest Aurora AWS RDS PG docs(some where i read) it says app shld always try to create new connections often as the connection string is load balanced  pg cluster especially readers, which means i may create a new object for let say background report generation and other connection for normal app queries using the same connection string how valid  is the warning in this case?

**Comment by PaulKushch** [comment] 2020-10-18 19:34
Anyone maybe use next.js? I follow the proposed pattern at https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise but I get the same warning as you guys, "creating a duplicate connection...". Maybe anyone have a solution?

**Comment by vitaly-t** [comment] 2020-10-18 20:30
@PaulKushch The warning includes the line where the repeated initialization occurs, so start from there.

**Comment by PaulKushch** [comment] 2020-10-18 21:10
@vitaly-t Yes, now the warning is not present, please see my code above. If I dont use singleton pattern, then the warning is there, with singleton pattern no warning. I use next.js...

**Comment by vitaly-t** [comment] 2020-10-18 21:26
Th reasonable solution is the one you quoted from StackOverflow :)

**Comment by PaulKushch** [comment] 2020-10-18 21:37
@vitaly-t In nextjs that solution gives warning.

**Comment by vitaly-t** [comment] 2020-10-18 22:09
That's an odd one, since NodeJS loads each module just once, so it is expected to be a singleton based on that.

**Comment by PaulKushch** [comment] 2020-10-19 06:56
@vitaly-t Yes I agree, I asked at next js repo. Anyway, thanks for the great library :)

**Comment by willieseabrook** [comment] 2021-01-14 22:23
I'm using nextjs and have that same problem with the warning message - that even when I use the best practice approach from stackoverflow it still gives the same warning.

FYI for anyone who finds this the nextjs discussion thread from PaulKushch is at https://github.com/vercel/next.js/discussions/18008 but as yet no answer.

@PaulKushch did you find a better solution other than the singleton pattern?

**Comment by PaulKushch** [comment] 2021-01-15 07:39
@willieseabrook No I just use the one above. It does seem not totally correct though...

**Comment by vitaly-t** [comment] 2021-01-15 08:15
I am re-opening this issue, just so I do not forget to have another look at it when I get a chance.

**Comment by willieseabrook** [comment] 2021-01-16 10:35
Thanks for your solution @PaulKushch. For anyone with the same nextjs pd-promise problem - I can confirm Paul's approach to a workaround works - I'm using it with nextjs and no longer get the error.

**Comment by vitaly-t** [comment] 2021-01-16 22:27
The following change was implemented and released in version `10.9.0` of the library...

Instead of using global `const` variables for internal pool repository, we are now using a `Symbol` on the `global` scope:

https://github.com/vitaly-t/pg-promise/blob/a8e94b80c0039db039e78e23c50e333688e5cd9f/lib/database-pool.js#L28

This should take care of the `WARNING: Creating a duplicate...` when modules are loaded in isolation.

---

For those who encountered the issue recently, please let us know if this update fixed it for you.

**Comment by vitaly-t** [comment] 2021-01-17 05:29
In version `10.9.1` I did the same for `QueryFile`, which also uses a singleton to detect and report duplicate file usage.

**Comment by vitaly-t** [comment] 2021-01-17 09:43
And in case this fix doesn't help, then the issue is not within the library, but definitely within the library you are using that breaks every singleton pattern in the app, by running modules multiple times. Let's see the feedback first.

**Comment by vitaly-t** [comment] 2021-01-17 22:27
Here's a simple helper one can use for creating a singleton namespace:

```js
/**
 * Retrieves or creates a singleton namespace/scope,
 * and optionally initializes it with default values.
 *
 * @param name
 * Globally-unique name for the scope.
 *
 * @param defaults
 * Optional object with default values-properties.
 *
 * @return {{}}
 * Singleton namespace/scope.
 */
function getSingleton(name, defaults) {
    const s = Symbol.for(name); // get global symbol
    let scope = global[s]; // get scope from the global
    if (!scope) {
        scope = {...defaults || {}}; // create singleton scope, with optional defaults
        global[s] = scope; // save our singleton in the global scope
    }
    return scope;
}
```

And inside a reusable module you can do something like this:

```js
function getDB() {
    // get singleton, set db and pgp in it, if for the first time:
    return getSingleton('my-app-singleton-space', {db, pgp});
}
```

module.exports = {getDB};

```

**Comment by vitaly-t** [comment] 2021-01-17 22:48
Here's a better approach, using TypeScript:

```ts
import * as pgLib from 'pg-promise';

const pgp = pgLib(/* initialization options */);

export function createSingleton<T>(name: string, create: () => T): T {
    const s = Symbol.for(name);
    let scope = (global as any)[s];
    if (!scope) {
        scope = {...create()};
        (global as any)[s] = scope;
    }
    return scope;
}

export interface DatabaseScope {
    pgp: pgLib.IMain;
    db: pgLib.IDatabase<any>;
}

export function getDB(): DatabaseScope {
    return createSingleton<DatabaseScope>('my-app-db-space', () => {
        return {
            pgp,
            db: pgp('my-connect-string')
        };
    });
}
```

**Comment by vitaly-t** [comment] 2021-01-19 03:54
I have updated the [popular question on StackOverflow about initialization](https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise).

If somebody still experiences an issue with al these updates, please le me know. in the meantime, I am closing this issue as resolved.

**Closed by vitaly-t** 2021-01-19 03:54 UTC
Labels: fixed, improvement, question

**Comment by MatthewJamesBoyle** [comment] 2021-01-23 12:40
Hey I upgraded to pg-promise 10.9.1 and used your code above to create a singleton. Unfortunately, I am still seing the 
`WARNING: Creating a duplicate database object for the same connection.` error message.
I'm running next 10.0.1 and here is my db code:
```
const pgp = require('pg-promise')();


// Get the values for these variables from configuration
const user = process.env.DB_USER
const password = process.env.DB_PASSWORD
const host = process.env.DB_HOST
const port = process.env.DB_PORT
const database = process.env.DB_NAME

const db = pgp(`postgres://${user}:${password}@${host}:${port}/${database}`);

function getSingleton(name, defaults) {
    const s = Symbol.for(name); // get global symbol
    let scope = global[s]; // get scope from the global
    if (!scope) {
        scope = {...defaults || {}}; // create singleton scope, with optional defaults
        global[s] = scope; // save our singleton in the global scope
    }
    return scope;
}

function getDB() {
    // get singleton, set db and pgp in it, if for the first time:
    return getSingleton('my-app-singleton-space', {db, pgp});
}


// module.exports = {getDB}
export default getDB;
```

**Comment by vitaly-t** [comment] 2021-01-23 13:04
@MatthewJamesBoyle Can you create a small demo app that shows the problem? At this point I cannot do anything without a reproducible example.

**Comment by MatthewJamesBoyle** [comment] 2021-01-23 13:20
@vitaly-t  sure leave it with me.

**Comment by MatthewJamesBoyle** [comment] 2021-01-23 13:28
@vitaly-t here you go: https://github.com/MatthewJamesBoyle/pg-promise-sample
run yarn and then yarn dev. If you navigate between localhost:3000 and localhost:3000/otherPage you should see the error in the dev console.

(you'll need to have a Postgres db setup with a users table, and a .env.local file with the following vars:
```
DB_USER
DB_PASSWORD
.DB_HOST
DB_PORT
DB_NAME
```

**Comment by vitaly-t** [comment] 2021-01-25 08:01
@MatthewJamesBoyle So basically, you took the singleton solution that I provided above, broke it in a few places, and then came back saying it doesn't work :smile:

What your code creates there is not a singleton at all. Please follow the singleton pattern that was given above.

`createSingleton` is supposed to invoke the callback when singleton is not set, and then inside that callback is where `db` is supposed to be created. You reverted all that, so your code now recreates the `db` whenever the module is loaded.

**Comment by MatthewJamesBoyle** [comment] 2021-01-25 08:49
> Here's a simple helper one can use for creating a singleton namespace:
> 
> ```js
> /**
>  * Retrieves or creates a singleton namespace/scope,
>  * and optionally initializes it with default values.
>  *
>  * @param name
>  * Globally-unique name for the scope.
>  *
>  * @param defaults
>  * Optional object with default values-properties.
>  *
>  * @return {{}}
>  * Singleton namespace/scope.
>  */
> function getSingleton(name, defaults) {
>     const s = Symbol.for(name); // get global symbol
>     let scope = global[s]; // get scope from the global
>     if (!scope) {
>         scope = {...defaults || {}}; // create singleton scope, with optional defaults
>         global[s] = scope; // save our singleton in the global scope
>     }
>     return scope;
> }
> ```
> 
> And inside a reusable module you can do something like this:
> 
> ```js
> function getDB() {
>     // get singleton, set db and pgp in it, if for the first time:
>     return getSingleton('my-app-singleton-space', {db, pgp});
> }
> 
> module.exports = {getDB};
> ```

@vitaly-t Not sure what you mean when you say "broke it in a few a few places" when I only made a single change to the code above which I copied and pasted? 

I have updated the example which is a direct copy and paste of the above. I still the issue unfortunately.

Appreciate you looking into it!

**Comment by vitaly-t** [comment] 2021-01-25 09:02
@MatthewJamesBoyle You are using the wrong example. I was referring to the last example, not what was posted earlier.

```js
// file db/index.ts

import * as pgLib from 'pg-promise';

const pgp = pgLib(/* initialization options */);

// generic singleton creator:
function createSingleton<T>(name: string, create: () => T): T {
    const s = Symbol.for(name);
    let scope = (global as any)[s];
    if (!scope) {
        scope = {...create()};
        (global as any)[s] = scope;
    }
    return scope;
}

interface IDatabaseScope {
    db: pgLib.IDatabase<any>;
    pgp: pgLib.IMain;
}

export function getDB(): IDatabaseScope {
    return createSingleton<IDatabaseScope>('my-app-db-space', () => {
        return {
            db: pgp('my-connect-string'),
            pgp
        };
    });
}
```

**Comment by MatthewJamesBoyle** [comment] 2021-01-25 09:04
@vitaly-t I didn't realise your previous example was invalid, might be best to remove it? My project doesn't use type script so opted for that. I will take a look at adapting that example shortly and see if it works, will report back :)

**Comment by vitaly-t** [comment] 2021-01-25 09:05
* I removed that example before you even posted this
* That example works in your code, which I tested here, couldn't commit the change though, as you didn't give me the rights.

**Comment by MatthewJamesBoyle** [comment] 2021-01-25 09:10
@vitaly-t hmm strange I could see that code until a few minutes ago on this discussion thread. Hence me quoting your reply above, as it was still visible. Glad its cleared up now though!

I added you as a  contributor to the project, thanks! I can tidy up the readme of it and can perhaps serve as an example for others using your great library with next.js

**Comment by vitaly-t** [comment] 2021-01-25 09:54
I won't have time for this today, you'll be better off just following the pattern as explained.

**Comment by vitaly-t** [comment] 2021-02-04 10:35
@MatthewJamesBoyle Did you get this working in the end?

**Comment by MatthewJamesBoyle** [comment] 2021-02-06 15:31
@vitaly-t no, I still get a development warning no matter what I try. I have moved to solve this problem with infrastructure instead for now.

**Comment by vitaly-t** [comment] 2021-02-06 15:55
Well, you probably did something wrong again then, because when I just followed that code example I provided, for your demo app, it just worked, there was no warning anymore. It works.

**Comment by MatthewJamesBoyle** [comment] 2021-02-06 15:56
Do you want to push it so I can see rather than just telling me I'm doing something wrong?

**Comment by vitaly-t** [comment] 2021-02-06 17:28
Sorry, didn't have time for code merging or writing it again,... [so I just zipped the result](https://filebin.net/5kbwhjqbv8xsk2m2).

**Comment by vitaly-t** [comment] 2021-02-06 17:36
I didn't have time to re-do it, so [here's zipped code](https://filebin.net/tfygoy31qw7pqwgp).

**Comment by markojanicic-sas** [comment] 2022-09-14 09:53
Hello, reopening 
@MatthewJamesBoyle did you solve this? Currently having the exact same issue. Would love to see your JS take on above solution.

**Comment by jcollum-nutrien** [comment] 2024-02-23 23:15
Here it is 5 months later and I'm seeing this issue in 11.5.4. Investigating, maybe we are doing something wrong in our code.
