### ISSUE TITLE
pgp.pg.defaults are not respected for pooling

### ISSUE THREAD

**Issue by bharkreader** [vitaly-t/pg-promise#703] opened 2020-03-18 05:27 UTC
### Expected behavior
pgp.pg.defaults.idleTimeoutMillis = 60000;
pgp.pg.defaults.max = 20;
dbInstance = pgp(CONFIG.dbConnectionString);
console.log(dbInstance.$pool.options.idleTimeoutMillis)
console.log(dbInstance.$pool.options.max)
// I expect it to print 60000 and 20

### Actual behavior
pgp.pg.defaults.idleTimeoutMillis = 60000;
pgp.pg.defaults.max = 20;
dbInstance = pgp(CONFIG.dbConnectionString);
console.log(dbInstance.$pool.options.idleTimeoutMillis)
console.log(dbInstance.$pool.options.max)
// it actually prints 10000 and 10

### Steps to reproduce
pgp.pg.defaults.idleTimeoutMillis = 60000;
pgp.pg.defaults.max = 20;
dbInstance = pgp(CONFIG.dbConnectionString);
console.log(dbInstance.$pool.options.idleTimeoutMillis)
console.log(dbInstance.$pool.options.max)

### Environment

* Version of pg-promise: 10.3.5
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.16.0

FWIW, I think this bug is a bug with pg-pool and I filed an issue there: https://github.com/brianc/node-postgres/issues/2139

But I'm not sure if or when it will get fixed, so we might want to update the documentation to mention that these values can be overridden by this instead:
```javascript
dbInstance.$pool.options.idleTimeoutMillis = 60000;
dbInstance.$pool.options.max = 20;
```

**Comment by vitaly-t** [comment] 2020-03-18 07:29
Seems like duplicate of #699

**Comment by bharkreader** [comment] 2020-03-18 18:22
Ah, yeah, you're right. Sorry I missed that. There is still a reference to overriding pgp.pg.defaults in the README which caused some confusion. Maybe we should update that? "or override the default via pgp.pg.defaults.idleTimeoutMillis"

**Comment by vitaly-t** [comment] 2020-03-19 07:44
>  There is still a reference to overriding pgp.pg.defaults in the README which caused some confusion

This has been amended.

**Comment by bharkreader** [comment] 2020-03-19 13:38
I think that's enough. Thanks!

**Comment by vitaly-t** [comment] 2020-03-19 14:10
Cheers!

**Closed by vitaly-t** 2020-03-19 14:10 UTC
Labels: dependency issue, duplicate

**Comment by vitaly-t** [comment] 2020-04-01 17:41
I have removed `idleTimeoutMillis` (within TypeScript) in [v10.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/10.5.0).
