### ISSUE TITLE
`none()` not waiting for transaction to be committed

### ISSUE THREAD

**Issue by daveisfera** [vitaly-t/pg-promise#444] opened 2018-01-11 00:03 UTC
The promise that's returned by `none()` doesn't appear to be waiting for the transaction to be committed. When we use `any()` instead, the expected result happens. Is this the expected behavior?

**Comment by daveisfera** [comment] 2018-01-11 00:46
Actually, further testing revealed that this was still an issue with `any()` but was just less likely to happen, so what is the proper way to be sure that the transaction is committed when the promise is resolved?

**Comment by vitaly-t** [comment] 2018-01-11 09:19
The issue is most likely with the way you do the transaction is done, so I need to see the code.

**Comment by vitaly-t** [comment] 2018-01-12 15:48
@daveisfera closing, due to the lack of the example. If you come back with an example, I will re-open the issue.

**Comment by daveisfera** [comment] 2018-01-12 20:35
We construct an array of arrays with the queries and data, `insertQueries` and then run the following:
```
return db.tx(t =>
    t.batch(_.map(insertQueries, queryValues => {
        const [query, values] = queryValues;
        return t.none(query, formatValues.concat(values));
    }))
);
```

Here's an example of `insertQueries`:
```
[
  [
    'INSERT INTO test AS a ($2~, $3~) VALUES $5^ ON CONFLICT ($2~) DO UPDATE SET value=EXCLUDED.value;',
    '(0, \'a\'), (1, \'b\'), (2, \'c\')'
  ] 
]
```

**Comment by vitaly-t** [comment] 2018-01-12 23:28
Interesting, that you use variables `$2, $3, $5`, but not `$1, $4`, that normally wouldn't work at all...

**Comment by daveisfera** [comment] 2018-01-12 23:55
Sorry, that's a mistake on my part. I stripped down our actual code a bit to make that example.

**Comment by vitaly-t** [comment] 2018-01-13 00:19
> Sorry, that's a mistake on my part. I stripped down our actual code a bit to make that example.

Are you going to show the complete version, as per my previous post? I can't help any further without it.

**Closed** 2018-01-15 17:39 UTC
Labels: needs clarification, question
